(source melpa-stable)
(source org)
(source gnu)

(depends-on "yaml-mode")
(depends-on "json-mode")

(depends-on "plantuml-mode")

(depends-on "haskell-mode")

(depends-on "go-autocomplete")
(depends-on "go-eldoc")
(depends-on "go-guru")
(depends-on "go-dlv")
(depends-on "go-mode")

(depends-on "exec-path-from-shell")
(depends-on "yasnippet")
(depends-on "guru-mode")
(depends-on "flycheck-gometalinter")
(depends-on "flycheck-title")
(depends-on "flycheck-pos-tip")
(depends-on "flycheck-color-mode-line")
(depends-on "flycheck")
(depends-on "magit")
(depends-on "auto-complete")

(depends-on "shut-up")
(depends-on "better-defaults")
(depends-on "multiple-cursors")
(depends-on "smex")

(depends-on "markdown-mode")
(depends-on "pandoc-mode")

(depends-on "dracula-theme")

(depends-on "pallet")

