#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

## Custom

prompt skwp

export GOPATH=$HOME/Projects/go
export GOBIN=$GOPATH/bin
export CASK_BIN=$HOME/.cask/bin
export PYTHON_USER_BIN=$HOME/Library/Python/2.7/bin
export HSANDBOX_BIN=$HOME/Projects/contrib/hsandbox
export PATH=$PATH:$GOBIN:$CASK_BIN:$PYTHON_USER_BIN:$HSANDBOX_BIN

export HSANDBOX_EDITOR=emacs

export CLICOLOR=1

eval "$(rbenv init -)"
