#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

## Custom

prompt skwp

export GOPATH=$HOME/Projects/go
export GOBIN=$GOPATH/bin
export CASK_BIN=$HOME/.cask/bin
export PATH=$PATH:$GOBIN:$CASK_BIN

export CLICOLOR=1
